<?php  
      //export.php  
 if(isset($_POST["export"]))  
 {  
      $connect=mysqli_connect("kidseduworldindia.com","kidsedu_kidsedu","Dec@2019$","kidsedu_kidzee");
      header('Content-Type: text/csv; charset=utf-8');  
      header('Content-Disposition: attachment; filename=data.csv');  
      $output = fopen("php://output", "w");  
      fputcsv($output, array('ID','Name of Child','New/Rollover/Re-join','Session','Accounting Year','Kidzee Enrollment No','Gender','Class','Form Fee','Mode of Payment','Form no','Bill Cum Receipt No','Indent No','Kit ordered','Kit Handed Over','Admission Confirmed Date','No. of Hours Comitted for Day care','No. of Installments Comitted','Stake Rate Fee','No. of Month for ES','Discount','Transaction Date of 1st Installment','1st Installment Amount','Mode of Payment','Cash/Cheque/Online Amount We received','Cheque/online No','Bill Cum Receipt No','Transaction Date of 2nd Installment','2nd Installment Amount','Mode of Payment','Cash/Cheque/Online Amount We received','Cheque/online No','Bill Cum Receipt No','Transaction Date of 3rd Installment','3rd Installment Amount','Mode of Payment','Cash/Cheque/Online Amount We received','Cheque/online No ','Bill Cum Receipt No','Transaction Date of 4th Installment','4th Installment Amount','Mode of Payment','Cash/Cheque/Online Amount We received','Cheque/online No','Bill Cum Receipt No','Transaction Date of 5th Installment','5th Installment Amount','Mode of Payment','Cash/Cheque/Online Amount We received','Cheque/online No','Bill Cum Receipt No','Transaction Date of 6th Installment','6th Installment Amount','Mode of Payment','Cash/Cheque/Online Amount We received','Cheque/online No','Bill Cum Receipt No','Transaction Date of 7th Installment','7th Installment Amount','Mode of Payment','Cash/Cheque/Online Amount We received','Cheque/online No','Bill Cum Receipt No','Transaction Date of 8th Installment','8th Installment Amount','Mode of Payment','Cash/Cheque/Online Amount We received ','Cheque/online No','Bill Cum Receipt No','Transaction Date of 9th Installment','9th Installment Amount','Mode of Payment','Cash/Cheque/Online Amount We received','Cheque/online No','Bill Cum Receipt No','Transaction Date of 10th Installment','10th Installment Amount','Mode of Payment','Cash/Cheque/Online Amount We received','Cheque/online No','Bill Cum Receipt No','Transaction Date of 11th Installment','11th Installment Amount','Mode of Payment','Cash/Cheque/Online Amount We received','Cheque/online No','Bill Cum Receipt No','Transaction Date of 12th Installment','12th Installment Amount','Mode of Payment','Cash/Cheque/Online Amount We received ','Cheque/online No','Bill Cum Receipt No ','Date','Cheque/Online','Cheque/Online Transaction No','Refund Amount','Cheque Dishonoured Number','Penalty Amount','Cheque Dishonoured Informed Parent Date','Next Dishonoured Amount','Mode of Payment for Dishonoured case','Cash/Cheque/Online Amount for Dishonoured Case','Bill Cum Receipt No for Dishonoured Case','Remarks','Pending','Date of Birth','Priliminary Kit','Uniform Handed Over','Father Name','Mother Name','Father Mobile Number','Mother Mobile Number','Father Email','Mother Email','Child Photo','Father photo','Mother photo','Child doc','Father doc','Mother doc','Society Name','Complete Address','Committed Fee'));  
      $query ="SELECT * FROM `add` ORDER BY admission_id ASC";    
      $result = mysqli_query($connect, $query);  
      while($row = mysqli_fetch_assoc($result))  
      {  
           fputcsv($output, $row);  
      }  
      fclose($output);  
 }  
 ?>  