<?php  
      //export.php  
 if(isset($_POST["export"]))  
 {  
      $connect = mysqli_connect("localhost", "root", "", "kidzee");  
      header('Content-Type: text/csv; charset=utf-8');  
      header('Content-Disposition: attachment; filename=data.csv');  
      $output = fopen("php://output", "w");  
      fputcsv($output, array(
                               'Child Id',  
                               'Form No',  
                               'Child No',  
                               'Name of Program',  
                               'Batch',  
                               'timing From ',  
                               'timing To ',  
                               'Child Photo ',  
                               'Father Photo ',  
                               'Mother Photo ',  
                               'Name of the Child ',  
                               'Gender  ', 
                               'Date of birth ',  
                               'Place of Birth  ',  
                               'height(cm) ',  
                               'Weight(kg) ',  
                               'Blood Group ',  
                               'Uniform Size Regular ',  
                               'Uniform Size Winter ',  
                               'Languages spoken at home ',  
                               'Address:House No ',  
                               'Street name ',  
                               'Area ',  
                               'Landmmark ',  
                               'City  ',  
                               'State  ',  
                               'Pin  ',  
                               'telephome number ',  
                               'Mobile number ',  
                               'Child Stay/live With ',  
                               'Mathers Name',  
                               'Mathers Resideantial:House No',  
                               'Mathers Street name',  
                               'Mathers Area',  
                               'Mathers Landmmark ',  
                               'Mathers City ',  
                               'Mathers State ',  
                               'Mathers Pin ',  
                               'Mathers Phone Number',  
                               'Mathers Occupation',  
                               'Mathers Qualification',  
                               'Mathers Designation',  
                               'Mathers Office Address',  
                               'Mathers office Pin',  
                               'Mathers Office Contact No',  
                               'Mathers Office Mobile NO',  
                               'Mathers Office Email',  
                               'Mathers Medial history',  
                               'Fathers Name',  
                               'Fathers Resideantial:House No',  
                               'Fathers Street name',  
                               'Fathers Area ',  
                               'Fathers Landmmark ',  
                               'Fathers City ',  
                               'Fathers State ',  
                               'Fathers Pin ',  
                               'Fathers Phone Number',  
                               'Fathers Occupation',  
                               'Fathers Qualification',  
                               'Fathers Designation',  
                               'Fathers Office Address',  
                               'Fathers Office Pin',  
                               'Fathers Office Contact No',  
                               'Fathers Office Mobile NO',  
                               'Fathers Office Email',  
                               'Fathers Medial history',  
                               'Sibling 1) Name ',  
                               'Sibling 1) gender ',  
                               'Sibling 1) Date of birth',  
                               'Sibling 1) School/attending',  
                               'Sibling 1) KIDZEE alumni',                                
							   'Sibling 2) Name ',  
                               'Sibling 2) gender ',  
                               'Sibling 2) Date of birth',  
                               'Sibling 2) School/attending',  
                               'Sibling 2) KIDZEE alumni',  
                               'Additional Member 1) Name  ',  
                               'Additional Member 1) gender',  
                               'Additional Member 1) relationship with child',  
                               'Additional Member 1) Date of birth',                                
							   'Additional Member 2) Name  ',  
                               'Additional Member 2) gender',  
                               'Additional Member 2) relationship with child',  
                               'Additional Member 2) Date of birth',  
                               'vaccine 1 ',  
                               'vaccine 2 ',  
                               'vaccine 3 ',  
                               'vaccine 4 ',  
                               'vaccine 5 ',  
                               'vaccine 6 ',  
                               'vaccine 7 ',  
                               'vaccine 8 ',  
                               'vaccine 9 ',  
                               'vaccine 10 ',  
                               'vaccine 11 ',  
                               'EMERGENCY CONTACT 1) NAME  ',  
                               'EMERGENCY CONTACT 1) Address ',  
                               'EMERGENCY CONTACT 1) PIN ',  
                               'EMERGENCY CONTACT 1) Home phone',  
                               'EMERGENCY CONTACT 1) Mobile NO',  
                               'EMERGENCY CONTACT 1) Email',  
                               'EMERGENCY CONTACT 1) Relationship with child',                                
							   'EMERGENCY CONTACT 2) NAME  ',  
                               'EMERGENCY CONTACT 2) Address ',  
                               'EMERGENCY CONTACT 2) PIN ',  
                               'EMERGENCY CONTACT 2) Home phone',  
                               'EMERGENCY CONTACT 2) Mobile NO',  
                               'EMERGENCY CONTACT 2) Email',  
                               'EMERGENCY CONTACT 2) Relationship with child',  
                               'Family Doctor Name ',  
                               'Family Doctor Address ',  
                               'Family Doctor PIN  ',  
                               'Family Doctor Home phone',  
                               'Family Doctor Mobile NO',  
                               'Family Doctor Email',  
                               'Does your cild have any allergies ',  
                               'if yes the please explain ',  
                               'does your child have any physical,emotional or behavioural issue that may interfere with his/her learning ',  
                               'if yes the please explain ',  
                               'At home does your child take an daily medication? ',  
                               'if yes the please explain ',  
                               'Is there any futhere information you feel we should know that may help us understand your child? ',  
                               'Any other comment ',  
                               'Office use Batch details',  
                               'Office use timing ',  
                               'Office use Date ',  
                               'Office use Invoice/receipt No',  
                               'Office use Amount'

	  ));  
       $query ="SELECT `child_id`, `F_no`, `child_no`, `program`, `batch`, `timeing_from`, `timeing_to`, `Image1`, `Image2`,
		`Image3`, `name_child`, `gender`, `dob`, `pob`, `height`, `weight`, `blood`, `uniform_reg`, `uniform_win`, `Lang`,
		`House`, `Street_name`, `Area`, `Landmmark`, `City`, `State`, `Pin`, `telephone`, `Mobile`, `Child_Stay`, `M_name`,
		`M_House`, `M_Street`, `M_Area`, `M_Landmmark`, `M_City`, `M_State`, `M_APin`, `M_Phone`, `M_Occupation`, 
		`M_Gualification`, `M_Designation`, `M_Office`, `M_OPin`, `M_Contact`, `M_Mobile`, `M_Email`, `M_Medial`, `F_name`,
		`F_House`, `F_Street`, `F_Area`, `F_Landmmark`, `F_City`, `F_State`, `F_APin`, `F_Phone`, `F_Occupation`,
		`F_Gualification`, `F_Designation`, `F_Office`, `F_OPin`, `F_Contact`, `F_Mobile`, `F_Email`, `F_Medial`, `1_Name`,
		`1_gender`, `1_dob`, `1_school`, `1_std`, `1_alumni`, `2_Name`, `2_gender`, `2_dob`, `2_school`, `2_std`, `2_alumni`,
		`01_Name`, `01_gender`, `01_relationship`, `01_dob`, `02_Name`, `02_gender`, `02_relationship`, `02_dob`, `v_1`,
		`v_2`, `v_3`, `v_4`, `v_5`, `v_6`, `v_7`, `v_8`, `v_9`, `v_10`, `v_11`, `E1_name`, `E1_address`, `E1_pin`, `E1_phone`,
		`E1_mobile`, `E1_email`, `E1__rela`, `E2_name`, `E2_address`, `E2_pin`, `E2_phone`, `E2_mobile`, `E2_email`,
		`E2__rela`, `DOC_name`, `DOC_add`, `DOC_pin`, `DOC_mobile`, `DOC_email`, `allergies`, `allergies_discp`, `issue`,
		`issue_discp`, `medication`, `medication_discp`, `understand`, `comment`, `Batch_detail`, `timing`, `date`,
		`invoice`, `amount` FROM `register`";  
      $result = mysqli_query($connect, $query);  
      while($row = mysqli_fetch_assoc($result))  
      {  
           fputcsv($output, $row);  
      }  
      fclose($output);  
 }  
 ?>  